# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbom < Formula
  desc "The Kubernetes Bill of Materials (KBOM) standard provides insight into container orchestration tools widely used across the industry."
  homepage "https://github.com/rad-security/kbom"
  version "0.3.4"
  license "Apache 2"

  on_macos do
    on_intel do
      url "https://github.com/rad-security/kbom/releases/download/v0.3.4/kbom_0.3.4_darwin_amd64.tar.gz"
      sha256 "bcd1ed4e492633ad08afc6241b96b046870d98dca6aeab40ed0a072a63bfecd6"

      def install
        bin.install "kbom"
      end
    end
    on_arm do
      url "https://github.com/rad-security/kbom/releases/download/v0.3.4/kbom_0.3.4_darwin_arm64.tar.gz"
      sha256 "d257f30b5d2da0a96cec48ad2d7c9a5bb30b6a0fbb94dbeb50e709109824692c"

      def install
        bin.install "kbom"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/kbom/releases/download/v0.3.4/kbom_0.3.4_linux_amd64.tar.gz"
        sha256 "acfdb3fa82e977de60a15141b2e9f54f47c6eb0c05d6a2276a960a81e2c85727"

        def install
          bin.install "kbom"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/kbom/releases/download/v0.3.4/kbom_0.3.4_linux_arm64.tar.gz"
        sha256 "84fb5439ed06575ba7e0c97b89f298223897bc926c254b87e4c766b79e9eb41b"

        def install
          bin.install "kbom"
        end
      end
    end
  end

  test do
    system "#{bin}/kbom", "version"
  end
end
