# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadImageScanner < Formula
  desc "Container image vulnerability scanner — wraps Grype with RAD Security enrichment"
  homepage "https://github.com/rad-security/image-scanner"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/rad-security/image-scanner/releases/download/v0.0.2/rad-image-scanner_0.0.2_darwin_amd64.tar.gz"
      sha256 "e470fa4864b2ad4b12931107604523a2a08ad8b54a2682d79bb1982a76cf8314"

      def install
        bin.install "rad-image-scanner"
      end
    end
    on_arm do
      url "https://github.com/rad-security/image-scanner/releases/download/v0.0.2/rad-image-scanner_0.0.2_darwin_arm64.tar.gz"
      sha256 "6e2e3f32434517c3f374d8b958eac2b14e496f0e50583987c31d1491bd91696c"

      def install
        bin.install "rad-image-scanner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/image-scanner/releases/download/v0.0.2/rad-image-scanner_0.0.2_linux_amd64.tar.gz"
        sha256 "ba7a8b9fbc5a649be243498b3c563a887e2afa196da274528b578b741a2e33f9"

        def install
          bin.install "rad-image-scanner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/image-scanner/releases/download/v0.0.2/rad-image-scanner_0.0.2_linux_arm64.tar.gz"
        sha256 "57f1d33c9220350904d2c9e53d0f5d7a600ae7233d23e968fc06cf2651925bde"

        def install
          bin.install "rad-image-scanner"
        end
      end
    end
  end

  test do
    system "#{bin}/rad-image-scanner", "--version"
  end
end
