# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadImageScanner < Formula
  desc "Container image vulnerability scanner — wraps Grype with RAD Security enrichment"
  homepage "https://github.com/rad-security/image-scanner"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/rad-security/image-scanner/releases/download/v0.0.4/rad-image-scanner_0.0.4_darwin_amd64.tar.gz"
      sha256 "b24973500b7ca553898dd93d1668485eef278c18c820861f710fa0b6cdb8b933"

      def install
        bin.install "rad-image-scanner"
      end
    end
    on_arm do
      url "https://github.com/rad-security/image-scanner/releases/download/v0.0.4/rad-image-scanner_0.0.4_darwin_arm64.tar.gz"
      sha256 "2565aa1eaeab42fa349b5a4f25fc644456c69cac4ba874ba5e259faa7cf8144a"

      def install
        bin.install "rad-image-scanner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/image-scanner/releases/download/v0.0.4/rad-image-scanner_0.0.4_linux_amd64.tar.gz"
        sha256 "9e6068ec1c7289847b4449a8f4ba814dc2cac95a3f44b6dd3e38c7df15f27790"

        def install
          bin.install "rad-image-scanner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/image-scanner/releases/download/v0.0.4/rad-image-scanner_0.0.4_linux_arm64.tar.gz"
        sha256 "b3634ab40b8070afe02823fb0db90f22e5c18bb88ac6eac45c23af9de5becc62"

        def install
          bin.install "rad-image-scanner"
        end
      end
    end
  end

  test do
    system "#{bin}/rad-image-scanner", "--version"
  end
end
