# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadImageScanner < Formula
  desc "Container image vulnerability scanner — wraps Grype with RAD Security enrichment"
  homepage "https://github.com/rad-security/image-scanner"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/rad-security/image-scanner/releases/download/v0.0.3/rad-image-scanner_0.0.3_darwin_amd64.tar.gz"
      sha256 "9a10b1b29ff41f4c93d2b4fcb48db60a7c86a13a0304ba6b7903495608282167"

      def install
        bin.install "rad-image-scanner"
      end
    end
    on_arm do
      url "https://github.com/rad-security/image-scanner/releases/download/v0.0.3/rad-image-scanner_0.0.3_darwin_arm64.tar.gz"
      sha256 "8a5d0cedfb034214c14c27731531c1cd1a7d407818252fde1daa9228f3ef688f"

      def install
        bin.install "rad-image-scanner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/image-scanner/releases/download/v0.0.3/rad-image-scanner_0.0.3_linux_amd64.tar.gz"
        sha256 "965281afe7668094a82badeed2c7d33c01cc37a766cb338bc63b73dfe0d812d0"

        def install
          bin.install "rad-image-scanner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/image-scanner/releases/download/v0.0.3/rad-image-scanner_0.0.3_linux_arm64.tar.gz"
        sha256 "48652f028fd5553750cd4c54ac7b58a5979f0095cb4aa553a059814035156b74"

        def install
          bin.install "rad-image-scanner"
        end
      end
    end
  end

  test do
    system "#{bin}/rad-image-scanner", "--version"
  end
end
